theme: jekyll-theme-cayman
<!DOCTYPE HTML>
<!-- Personal Website by Zhepei Wang -->
<html>

<head>
  <meta charset="UTF-8">
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,italic,700,400,600' rel='stylesheet'
    type='text/css'>
  <link rel="stylesheet" type="text/css" href="style.css" />
  <title>Zhepei Wang</title>
</head>

<body>
  <div class="page">
    <h1>Zhepei Wang</h1>
    <div class="intro">
      <div class="portrait">
        <img src="figs/wzp.jpg" width="300" height="401">
        <p align="center">[<a href="mailto:wangzhepei@live.com">wangzhepei@live.com</a>
          | <a href="https://github.com/ZhepeiWang">github</a>]</p>
      </div>
      <div class="intro_text">
        <p>Hey, my name is Zhepei. I'm passionate about autonomous vehicles, mathematical programming, and computational
          geometry.
          I received my Ph.D. degree in Control Science and Engineering from the <a
            href="http://www.zju.edu.cn/">Zhejiang University</a>
          in 2022, for my work on motion planning for flying robots under the supervision of
          <a href="https://scholar.google.com/citations?user=4RObDv0AAAAJ&hl=en&oi=ao">Fei Gao</a> and
          <a href="https://person.zju.edu.cn/xu">Chao Xu</a> at the <a href="http://zju-fast.com/">ZJU-FAST-Lab</a>.
          I received my B.Eng. degree in Automation from the <a href="http://www.cse.zju.edu.cn/">College of Control
            Science and
            Engineering</a>, Zhejiang University, in 2017.
        </p>
        <p>Selected: <a href="https://github.com/ZJU-FAST-Lab/GCOPTER">
            A General-Purpose Trajectory Optimizer for Multicopters</a></p>
        <a href="https://github.com/ZJU-FAST-Lab/GCOPTER" target="blank">
          <p align="center">
            <img src="figs/gcopter_se3task_cover.png" width="85%" />
          </p>
        </a>
      </div>
    </div>
  </div>

  <div class="page">
    <h1>Publications</h1>
    <div class="pub_list">
      <p>Zhepei Wang, Xin Zhou, Chao Xu, and Fei Gao, “<b>Geometrically Constrained Trajectory Optimization for
          Multicopters</b>”. <i>IEEE Transactions on Robotics (<b>T-RO</b>)</i>, Regular Paper, 2022. <br>
        [ <a href="pubs/tro_2022_gcopter.pdf">pdf</a>
        | <a href="https://www.youtube.com/watch?v=QQS0AM3iOmc">video 0</a>
        | <a href="https://www.youtube.com/watch?v=pQ4oSf1rdBU">video 1</a>
        | <a href="https://doi.org/10.1109/TRO.2022.3160022">publisher link</a>] <br>

        (Reported by <a href="https://spectrum.ieee.org/">IEEE Spectrum Website</a>)
      </p>
      <p>Xin Zhou, Xiangyong Wen, Zhepei Wang, Yuman Gao, Haojia Li, Qianhao Wang, Tiankai Yang,
        Haojian Lu, Yanjun Cao, Chao Xu, and Fei Gao, “<b>Swarm of Micro Flying Robots in the Wild</b>”.
        <i>Science Robotics (<b>SciRob</b>)</i>, 2022.<br>
        [ <a href="pubs/sr_2022_swarm.pdf">pdf</a>
        | <a href="https://www.youtube.com/watch?v=L0fJ0EHHfOA">video</a>
        | <a href="https://doi.org/10.1126/scirobotics.abm5954">publisher link</a>]
      </p>
      <p>Zhepei Wang, Hongkai Ye, Chao Xu, and Fei Gao, “<b>Generating Large-Scale Trajectories Efficiently using
          Double Descriptions of Polynomials</b>”. <i>IEEE International Conference on Robotics and Automation
          (<b>ICRA</b>)</i>,
        2021.<br>
        [ <a href="pubs/icra_2021_largescale.pdf">pdf</a>
        | <a href="pubs/icra_2021_largetraj_bibtex.txt">bibtex</a>
        | <a href="https://www.youtube.com/watch?v=tA3fIyggH4I">video</a>
        | <a href="https://doi.org/10.1109/ICRA48506.2021.9561585">publisher link</a>]
      </p>
      <p>Xin Zhou, Zhepei Wang, Hongkai Ye, Chao Xu, and Fei Gao, “<b>EGO-Planner: An ESDF-free Gradient-based Local
          Planner for Quadrotors</b>”. <i>IEEE Robotics and Automation Letters (<b>RA-L</b>)</i>, 2021. <br>
        [ <a href="pubs/ral_2021_egoplan.pdf">pdf</a>
        | <a href="pubs/ral_2021_egoplan_bibtex.txt">bibtex</a>
        | <a href="https://www.youtube.com/watch?v=UKoaGW7t7Dk&feature=youtu.be">video</a>
        | <a href="https://doi.org/10.1109/LRA.2020.3047728">publisher link</a>] <br>
        (Reported by <a href="https://spectrum.ieee.org/">IEEE Spectrum Website</a>)
      </p>
      <p>Jialin Ji*, Zhepei Wang*, Yingjian Wang, Chao Xu, and Fei Gao, “<b>Mapless-Planner: A Robust and Fast Planning
          Framework for Aggressive Autonomous Flight without Map Fusion</b>”. <i>IEEE International Conference on
          Robotics and Automation (<b>ICRA</b>)</i>, 2021.<br>
        [ <a href="pubs/icra_2021_mapless.pdf">pdf</a>
        | <a href="pubs/icra_2021_mapless_bibtex.txt">bibtex</a>
        | <a href="https://www.youtube.com/watch?v=kjIJe6MrjsU">video</a>
        | <a href="https://doi.org/10.1109/ICRA48506.2021.9561460">publisher link</a>] (*Co-First Authors)
      </p>
      <p>Zhepei Wang, Xin Zhou, Chao Xu, Jian Chu, and Fei Gao, “<b>Alternating Minimization Based Trajectory Generation
          for Quadrotor Aggressive Flight</b>”. <i>IEEE Robotics and Automation Letters (<b>RA-L</b>)</i>, 2020,
        and also in <i>IEEE/RSJ International Conference on Intelligent Robots and Systems (<b>IROS</b>)</i>, 2020.<br>
        [ <a href="pubs/ral_2020_amtraj.pdf">pdf</a>
        | <a href="pubs/ral_2020_amtraj_bibtex.txt">bibtex</a>
        | <a href="https://www.youtube.com/watch?v=H89ALyWA2NI&feature=youtu.be">video</a>
        | <a href="https://doi.org/10.1109/LRA.2020.3003871">publisher link</a>]
      </p>
      <p>Zhepei Wang, Chao Xu, and Fei Gao, “<b>Robust Trajectory Planning for Spatial-Temporal Multi-Drone Coordination
          in Large Scenes</b>”. <i>IEEE/RSJ International Conference on Intelligent Robots and Systems
          (<b>IROS</b>)</i>, 2022.<br>
        [ <a href="pubs/iros_2022_robustdrag.pdf">pdf</a>
        | <a href="https://www.youtube.com/watch?v=670QxGBnvyM">video</a>
        | <a href="https://arxiv.org/abs/2109.08403">arxiv link</a>]
      </p>
      <p>Zhichao Han, Zhepei Wang, Neng Pan, Yi Lin, Chao Xu, and Fei Gao, “<b>Fast-Racing: An Open-source Strong
          Baseline for SE(3) Planning in Autonomous Drone Racing</b>”. <i>IEEE Robotics and Automation Letters
          (<b>RA-L</b>)</i>, 2021. <br>
        [ <a href="pubs/ral_2021_se3race.pdf">pdf</a>
        | <a href="pubs/ral_2021_se3race_bibtex.txt">bibtex</a>
        | <a href="https://www.youtube.com/watch?v=oIqtN3zWIhM">video</a>
        | <a href="https://doi.org/10.1109/LRA.2021.3113976">publisher link</a>]
      </p>
      <p>Xin Zhou, Zhepei Wang, Xiangyong Wen, Jiangchao Zhu, Chao Xu, and Fei Gao, “<b>Decentralized Spatial-Temporal
          Trajectory Planning for Multicopter Swarms</b>”. <i>Technical Report</i>, 2021. <br>
        [ <a href="pubs/techrep_2021_dsto.pdf">pdf</a>
        | <a href="https://www.youtube.com/watch?v=w5GDMpjAoVQ">video</a>
        | <a href="https://arxiv.org/abs/2106.12481">arxiv link</a>] <br>
        (Reported by <a href="https://spectrum.ieee.org/">IEEE Spectrum Website</a>)
      </p>
      <p>Hongkai Ye, Xin Zhou, Zhepei Wang, Chao Xu, Jian Chu, and Fei Gao, “<b>TGK-Planner: An Efficient Topology
          Guided Kinodynamic Planner for Autonomous Quadrotors</b>”. <i>IEEE Robotics and Automation Letters
          (<b>RA-L</b>)</i>,
        2021.<br>
        [ <a href="pubs/ral_2021_tgkplan.pdf">pdf</a>
        | <a href="pubs/ral_2021_tgkplan_bibtex.txt">bibtex</a>
        | <a href="https://www.youtube.com/watch?v=nNS0p8h5zAk&feature=youtu.be">video</a>
        | <a href="https://doi.org/10.1109/LRA.2020.3047798">publisher link</a>]
      </p>
      <p>Shaohui Yang, Botao He, Zhepei Wang, Chao Xu, and Fei Gao, “<b>Whole-Body Real-Time Motion Planning for
          Multicopters</b>”. <i>IEEE International Conference on Robotics and Automation (<b>ICRA</b>)</i>, 2021.<br>
        [ <a href="pubs/icra_2021_wholebody.pdf">pdf</a>
        | <a href="pubs/icra_2021_wholebody_bibtex.txt">bibtex</a>
        | <a href="https://www.youtube.com/watch?v=tkhN6Xrxluk">video</a>
        | <a href="https://doi.org/10.1109/ICRA48506.2021.9561526">publisher link</a>]
      </p>
      <p>Yunfan Ren, Fangcheng Zhu, Wenyi Liu, Zhepei Wang, Yi Lin, Fei Gao, and Fu Zhang,
        “<b>Bubble Planner: Planning High-speed Smooth Quadrotor Trajectories using Receding Corridors</b>”.
        <i>IEEE/RSJ International Conference on Intelligent Robots and Systems (<b>IROS</b>)</i>, 2022. <br>
        [ <a href="pubs/sub_2022_bubble.pdf">pdf</a>
        | <a href="https://www.youtube.com/watch?v=GpATPwibJ1k">video</a>
        | <a href="https://arxiv.org/abs/2202.12177">arxiv link</a>]
      </p>
      <p>Tianyu Liu, Qianhao Wang, Xingguang Zhong, Zhepei Wang, Chao Xu, and Fei Gao, “<b>Star-Convex Constrained
          Optimization for Visibility Planning with Application to Aerial Inspection</b>”. <i>IEEE
          International Conference on Robotics and Automation (<b>ICRA</b>)</i>, 2022.<br>
        [ <a href="pubs/icra_2022_starcons.pdf">pdf</a>
        | <a href="https://www.youtube.com/watch?v=0ejW2GomYjk">video</a>]
      </p>
      <p>Jiangcheng Zhu, Jun Zhu, Zhepei Wang, Shan Guo, and Chao Xu, “<b>Hierarchical Decision and Control for
          Continuous Multitarget Problem: Policy Evaluation With Action Delay</b>”. <i>IEEE Transactions on Neural
          Networks and Learning Systems (<b>T-NNLS</b>)</i>, 2018.<br>
        [ <a href="pubs/tnnls_2018_hierarchical.pdf">pdf</a>
        | <a href="pubs/tnnls_2018_hierarchical.txt">bibtex</a>
        | <a href="https://doi.org/10.1109/TNNLS.2018.2844466">publisher link</a>]
      </p>
    </div>
  </div>
</body>

</html>
